apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: web-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: lb-test
        image: strm/helloworld-http
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: web
  annotations:
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: web
  type: LoadBalancer
